### ISSUE TITLE
Lodash deduping

### ISSUE THREAD

**Issue by brokentone** [CondeNast/jsonmltoreact#3]
Package uses two sub packages of lodash on different major versions.

```
    "lodash.camelcase": "^4.1.1",
    "lodash.isfunction": "^3.0.8"
```

~~For weight, these MINIMALLY should be the same major so that they can use the same copy of lodash core.~~

edit: I lied, lodash sub packages don't seem to rely on lodash core as a dep, and thus can't dedupe.

For Conde, we know we all need all of lodash and these sub-packages don't dedupe against full lodash. I would recommend we actually go to straight lodash to allow for the best de-duping with brand apps.

**Comment by diffcunha** [comment]
I see your point but `lodash` full build is around 23kB gzipped. It definitely makes to dedupe dependencies but including non used `lodash` methods doesn't really. To go really minimal with `lodash` there are only 2 ways: cherry picking methods all the time or using something like `babel-plugin-lodash` (though it only works with ES2015 named imports and most of our code is using either `require('lodash')` or `import _ from 'lodash'` and calling the methods with `_.method`). In any case, as this is Condé repo, I'm ok with the change to full `lodash` as it is probably the best approach for now

**Comment by pgoldrbx** [comment]
Fixed by https://github.com/CondeNast/jsonmltoreact/pull/7
